use_frameworks!

target 'LPDTableViewKit_Example' do
  pod 'LPDTableViewKit', :path => '../'
  pod 'LPDNetworkingKit'
  pod 'LPDAdditionsKit'
  pod 'Masonry'
  pod 'MLeaksFinder'

  target 'LPDTableViewKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
